// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbkmZI63ilxLMhgPEiRtnbk0hti73If0',
    appId: '1:1069475991671:web:b71e094be70785c4083672',
    messagingSenderId: '1069475991671',
    projectId: 'temubatik',
    authDomain: 'temubatik.firebaseapp.com',
    storageBucket: 'temubatik.firebasestorage.app',
    measurementId: 'G-7MYTTK11M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OcRleWggq58hZFRsx-GA1dFbGAcbJjY',
    appId: '1:1069475991671:android:46cd5d6068ba7c91083672',
    messagingSenderId: '1069475991671',
    projectId: 'temubatik',
    storageBucket: 'temubatik.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHbkmZI63ilxLMhgPEiRtnbk0hti73If0',
    appId: '1:1069475991671:web:008c7f79aaba4c12083672',
    messagingSenderId: '1069475991671',
    projectId: 'temubatik',
    authDomain: 'temubatik.firebaseapp.com',
    storageBucket: 'temubatik.firebasestorage.app',
    measurementId: 'G-D6B898CKRX',
  );
}
